# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29c67a0f6105327c3a3a67c42ff9c8156151fc465b80d585ade8711aae571c87725528f533adb561103d7381e54b2c8cc0300c1e34f85e80b1778a353e0bc202

test:
  secret_key_base: 83b06a29649718f2c69234ab0dda69c421b2b76f08b14f7ed41dd79cc5f41bdb16b9fdf5cba79e9352721cd30a623c01abab63273e475aeff726d8bfd26ceba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
